# Generated by Django 3.2.3 on 2021-06-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calaccess_raw', '0018_auto_20210426_2015'),
        ('calaccess_processed', '0015_auto_20180416_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataVersionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('calaccess_raw.rawdataversion',),
        ),
    ]
