# Generated by Django 3.2.4 on 2021-06-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calaccess_raw', '0018_auto_20210426_2015'),
        ('calaccess_scraped', '0003_auto_20210426_2334'),
        ('calaccess_processed', '0015_auto_20180416_2200'),
        ('calaccess_processed_filings', '0011_auto_20210426_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataVersionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('calaccess_raw.rawdataversion',),
        ),
    ]
