# Generated by Django 3.2.4 on 2021-06-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0016_auto_20210619_1139'),
        ('calaccess_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDataVersionProxy',
            fields=[
                ('processeddataversion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calaccess_processed.processeddataversion')),
            ],
            bases=('calaccess_processed.processeddataversion',),
        ),
    ]
