# Generated by Django 3.2.4 on 2021-06-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0016_auto_20210619_1139'),
        ('calaccess_website', '0002_processeddataversionproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedDataVersionProxy',
        ),
        migrations.CreateModel(
            name='ProcessedDataVersionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('calaccess_processed.processeddataversion',),
        ),
    ]
