name: Extract, transform and load
on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"

jobs:
  etl:
    name: "ETL"
    runs-on: self-hosted

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: calaccess_website
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - id: pipenv-install
        name: Install Python dependencies
        run: pipenv install --python 3.9 --skip-lock

      - name: Set Django settings
        run: cp project/settings_actions.py.template project/settings_local.py
        shell: bash

      - name: Migrate database
        run: pipenv run python -W ignore manage.py migrate;
        shell: bash
        env:
          PGPASSWORD: postgres

      - name: Load scraped data
        run: pipenv run python -W ignore manage.py loadcalaccessscrapeddata --verbosity=3;
        shell: bash
        env:
          PGPASSWORD: postgres

      - name: Update raw and processed data
        run: pipenv run python -W ignore manage.py updatedownloadswebsite --keep-files --noinput --verbosity=3;
        shell: bash
        env:
          PGPASSWORD: postgres

      - name: Upload source download as artifact
        uses: actions/upload-artifact@v3
        with:
          name: source
          path: data/download
          if-no-files-found: error

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: data/log
          if-no-files-found: error

      - name: Upload raw files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: raw-data
          path: data/csv
          if-no-files-found: error

      - name: Upload processed files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: processed-data
          path: data/processed
          if-no-files-found: error

      - name: Upload all files to biglocalnews.org
        uses: biglocalnews/upload-files@v2
        with:
          api-key: ${{ secrets.BLN_API_TOKEN }}
          project-id: ${{ secrets.BLN_PROJECT_ID }}
          path: ./data/
